# Step 1: Use a Node image to build the Angular app
FROM node:18 AS build

  # Set working directory
WORKDIR /app

  # Copy package.json and package-lock.json
COPY package*.json ./

  # Install dependencies
RUN npm install

  # Copy the Angular project files to the container
COPY . .

  # Build the Angular app
RUN npm run build --prod

  # Step 2: Use a lightweight web server to serve the app
FROM nginx:alpine

  # Copy the Angular build output to the Nginx HTML directory
COPY --from=build /app/dist/<your-app-name> /usr/share/nginx/html

  # Expose the default Nginx port
EXPOSE 80

  # Start Nginx
CMD ["nginx", "-g", "daemon off;"]
